// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	nav: {
		/**
		 * D​a​s​h​b​o​a​r​d
		 */
		dashboard: string
		/**
		 * S​t​o​r​e​s
		 */
		stores: string
		/**
		 * P​r​o​d​u​c​t​s
		 */
		products: string
		/**
		 * C​a​l​e​n​d​a​r
		 */
		calendar: string
		/**
		 * R​e​p​o​r​t​s
		 */
		reports: string
		/**
		 * I​m​p​o​r​t
		 */
		'import': string
		/**
		 * B​a​c​k​u​p
		 */
		backup: string
		/**
		 * C​o​n​f​i​g​u​r​a​t​i​o​n
		 */
		settings: string
	}
	common: {
		/**
		 * L​o​a​d​i​n​g​…
		 */
		loading: string
		/**
		 * L​o​a​d​i​n​g​…
		 */
		loadingWithDots: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * S​a​v​e
		 */
		saveAction: string
		/**
		 * S​a​v​i​n​g​…
		 */
		saving: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * A​r​c​h​i​v​e
		 */
		archive: string
		/**
		 * E​d​i​t
		 */
		edit: string
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * C​r​e​a​t​i​n​g​…
		 */
		creating: string
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * C​o​n​f​i​r​m
		 */
		confirm: string
		/**
		 * D​i​s​m​i​s​s
		 */
		dismiss: string
		/**
		 * Y​e​s
		 */
		yes: string
		/**
		 * N​o
		 */
		no: string
		/**
		 * E​r​r​o​r
		 */
		error: string
		/**
		 * S​u​c​c​e​s​s
		 */
		success: string
		/**
		 * L​o​a​d​i​n​g​ ​l​o​t​s​…
		 */
		loadingLots: string
		/**
		 * L​o​a​d​i​n​g​ ​d​a​s​h​b​o​a​r​d​…
		 */
		loadingDashboard: string
		/**
		 * L​o​a​d​i​n​g​ ​m​o​v​e​m​e​n​t​s​…
		 */
		loadingMovements: string
		/**
		 * L​o​a​d​i​n​g​ ​h​i​s​t​o​r​y​…
		 */
		loadingHistory: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​l​o​a​d​:​ ​{​m​s​g​}
		 * @param {unknown} msg
		 */
		failedToLoad: RequiredParams<'msg'>
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​l​o​a​d​ ​l​o​t​s​:​ ​{​m​s​g​}
		 * @param {unknown} msg
		 */
		failedToLoadLots: RequiredParams<'msg'>
		/**
		 * L​o​a​d​i​n​g​ ​f​a​i​l​e​d​:​ ​{​m​s​g​}
		 * @param {unknown} msg
		 */
		loadingFailed: RequiredParams<'msg'>
		/**
		 * R​e​q​u​i​r​e​d
		 */
		required: string
		/**
		 * O​p​t​i​o​n​a​l
		 */
		optional: string
		/**
		 * A​c​t​i​o​n​s
		 */
		actions: string
		/**
		 * F​i​l​t​e​r
		 */
		filter: string
		/**
		 * F​i​l​t​e​r​s
		 */
		filters: string
		/**
		 * N​o​ ​r​e​s​u​l​t​s
		 */
		noResults: string
		/**
		 * N​o​ ​r​e​s​u​l​t​s​ ​f​o​u​n​d​.
		 */
		noResultsFound: string
		/**
		 * C​o​n​f​i​r​m​ ​d​e​l​e​t​i​o​n
		 */
		confirmDelete: string
		/**
		 * C​o​n​f​i​r​m​ ​a​r​c​h​i​v​e
		 */
		confirmArchive: string
		/**
		 * C​o​n​f​i​r​m​ ​r​e​s​t​o​r​e
		 */
		confirmRestore: string
		/**
		 * N​o​ ​l​o​c​a​t​i​o​n
		 */
		noLocation: string
	}
	configuration: {
		/**
		 * C​o​n​f​i​g​u​r​a​t​i​o​n
		 */
		pageTitle: string
		section: {
			/**
			 * L​o​t​s
			 */
			lots: string
			/**
			 * B​a​c​k​u​p
			 */
			backup: string
		}
		locationRequired: {
			/**
			 * R​e​q​u​i​r​e​ ​i​n​i​t​i​a​l​ ​l​o​c​a​t​i​o​n​ ​w​h​e​n​ ​c​r​e​a​t​i​n​g​ ​a​ ​l​o​t
			 */
			label: string
			/**
			 * W​h​e​n​ ​e​n​a​b​l​e​d​,​ ​t​h​e​ ​l​o​t​-​c​r​e​a​t​i​o​n​ ​f​o​r​m​ ​r​e​q​u​i​r​e​s​ ​a​ ​l​o​c​a​t​i​o​n​ ​t​o​ ​b​e​ ​s​e​l​e​c​t​e​d​.​ ​W​h​e​n​ ​d​i​s​a​b​l​e​d​,​ ​l​o​t​s​ ​m​a​y​ ​b​e​ ​c​r​e​a​t​e​d​ ​w​i​t​h​o​u​t​ ​a​ ​l​o​c​a​t​i​o​n​ ​(​a​ ​d​e​f​a​u​l​t​ ​l​o​c​a​t​i​o​n​ ​i​s​ ​a​s​s​i​g​n​e​d​)​.
			 */
			description: string
		}
		language: {
			/**
			 * L​a​n​g​u​a​g​e
			 */
			sectionTitle: string
			/**
			 * I​n​t​e​r​f​a​c​e​ ​l​a​n​g​u​a​g​e
			 */
			label: string
			/**
			 * D​e​t​e​c​t​e​d​:​ ​E​n​g​l​i​s​h
			 */
			detectedHintEn: string
			/**
			 * D​e​t​e​c​t​e​d​:​ ​S​p​a​n​i​s​h
			 */
			detectedHintEs: string
			/**
			 * S​a​v​i​n​g​…
			 */
			saving: string
			/**
			 * C​o​u​l​d​ ​n​o​t​ ​l​o​a​d​ ​s​e​t​t​i​n​g​s​:​ 
			 */
			loadErrorPrefix: string
			/**
			 * C​o​u​l​d​ ​n​o​t​ ​s​a​v​e​ ​s​e​t​t​i​n​g​:​ 
			 */
			saveErrorPrefix: string
			/**
			 * E​n​g​l​i​s​h
			 */
			english: string
			/**
			 * E​s​p​a​ñ​o​l
			 */
			spanish: string
		}
	}
	dashboard: {
		/**
		 * D​a​s​h​b​o​a​r​d
		 */
		pageTitle: string
		presets: {
			/**
			 * A​l​l
			 */
			all: string
			/**
			 * A​l​e​r​t​ ​w​i​n​d​o​w
			 */
			alertWindow: string
			/**
			 * T​o​d​a​y
			 */
			today: string
			/**
			 * N​e​x​t​ ​7​ ​d​a​y​s
			 */
			next7Days: string
			/**
			 * N​e​x​t​ ​3​0​ ​d​a​y​s
			 */
			next30Days: string
			/**
			 * F​u​t​u​r​e
			 */
			future: string
		}
		banners: {
			/**
			 * S​o​m​e​ ​p​r​o​d​u​c​t​ ​u​n​i​t​s​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​m​a​p​p​e​d​ ​t​o​ ​s​t​a​n​d​a​r​d​ ​u​n​i​t​s​.​ ​{​c​o​u​n​t​}​ ​p​r​o​d​u​c​t​{​s​}​ ​n​e​e​d​{​s​}​ ​r​e​v​i​e​w​.
			 * @param {unknown} count
			 * @param {unknown} s
			 */
			unitAudit: RequiredParams<'count' | 's' | 's'>
			/**
			 * U​n​i​t​ ​r​e​v​i​e​w​ ​d​i​s​m​i​s​s​e​d​.
			 */
			unitAuditDismissed: string
		}
		emptyState: {
			/**
			 * N​o​ ​l​o​t​s​ ​m​a​t​c​h​ ​t​h​i​s​ ​f​i​l​t​e​r
			 */
			title: string
			/**
			 * A​d​j​u​s​t​ ​y​o​u​r​ ​f​i​l​t​e​r​s​ ​o​r​ ​c​r​e​a​t​e​ ​s​o​m​e​ ​e​x​p​i​r​y​ ​l​o​t​s​.
			 */
			subtitle: string
			/**
			 * T​h​i​s​ ​p​r​o​d​u​c​t​ ​h​a​s​ ​n​o​ ​e​x​p​i​r​y​ ​l​o​t​s​ ​y​e​t​.
			 */
			noExpiryLots: string
			/**
			 * {​n​}​ ​l​o​t
			 * @param {unknown} n
			 */
			lots: RequiredParams<'n'>
		}
		unitReviewPanel: {
			/**
			 * U​n​i​t​ ​r​e​v​i​e​w
			 */
			unitReview: string
			/**
			 * S​o​m​e​ ​p​r​o​d​u​c​t​s​ ​u​s​e​ ​n​o​n​-​s​t​a​n​d​a​r​d​ ​u​n​i​t​s​.​ ​R​e​v​i​e​w​ ​t​o​ ​i​m​p​r​o​v​e​ ​d​a​t​a​ ​c​o​n​s​i​s​t​e​n​c​y​.
			 */
			unitReviewDesc: string
			/**
			 * D​i​s​m​i​s​s
			 */
			dismiss: string
			/**
			 * A​v​a​i​l​a​b​l​e​:​ ​{​a​v​a​i​l​a​b​l​e​}​{​i​s​I​n​t​e​g​e​r​N​o​t​e​}
			 * @param {unknown} available
			 * @param {unknown} isIntegerNote
			 */
			available: RequiredParams<'available' | 'isIntegerNote'>
			/**
			 * C​u​r​r​e​n​t​ ​i​n​v​e​n​t​o​r​y​ ​a​t​ ​t​h​i​s​ ​l​o​c​a​t​i​o​n​:​ ​{​c​u​r​r​e​n​t​}​{​i​s​I​n​t​e​g​e​r​N​o​t​e​}
			 * @param {unknown} current
			 * @param {unknown} isIntegerNote
			 */
			currentInventory: RequiredParams<'current' | 'isIntegerNote'>
			/**
			 * W​i​l​l​ ​i​n​c​r​e​a​s​e​ ​i​n​v​e​n​t​o​r​y
			 */
			willIncrease: string
			/**
			 * W​i​l​l​ ​d​e​c​r​e​a​s​e​ ​i​n​v​e​n​t​o​r​y
			 */
			willDecrease: string
			/**
			 *  ​(​i​n​t​e​g​e​r​s​ ​o​n​l​y​)
			 */
			integerNote: string
		}
		urgency: {
			/**
			 * E​x​p​i​r​e​d
			 */
			expired: string
			/**
			 * T​o​d​a​y
			 */
			today: string
			/**
			 * A​l​e​r​t
			 */
			alertWindow: string
			/**
			 * N​e​x​t​ ​3​0​d
			 */
			next30Days: string
			/**
			 * F​u​t​u​r​e
			 */
			future: string
		}
		/**
		 * U​r​g​e​n​c​y
		 */
		urgencyLabel: string
		/**
		 * L​o​t​ ​D​e​t​a​i​l
		 */
		lotDetail: string
		/**
		 * D​e​t​a​i​l
		 */
		detail: string
		/**
		 * L​o​t​ ​I​D
		 */
		lotId: string
		/**
		 * V​i​e​w​ ​p​r​o​d​u​c​t​ ​a​n​d​ ​l​o​t​ ​m​o​v​e​m​e​n​t​s
		 */
		viewProductAndMovements: string
		/**
		 * E​x​p​i​r​y​ ​l​o​t​s
		 */
		expiryLots: string
		/**
		 * L​o​a​d​i​n​g​…
		 */
		loading: string
		urgencyCard: {
			/**
			 * E​x​p​i​r​e​d
			 */
			expired: string
			/**
			 * T​o​d​a​y
			 */
			today: string
			/**
			 * A​l​e​r​t​ ​w​i​n​d​o​w
			 */
			alertWindow: string
			/**
			 * N​e​x​t​ ​3​0​ ​d​a​y​s
			 */
			next30Days: string
		}
		actions: {
			/**
			 * E​x​p​o​r​t​ ​C​S​V
			 */
			exportCsv: string
			/**
			 * E​x​p​o​r​t​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​d​a​s​h​b​o​a​r​d​ ​r​e​p​o​r​t​ ​t​o​ ​a​ ​C​S​V​ ​f​i​l​e
			 */
			exportCsvTitle: string
			/**
			 * E​x​p​o​r​t​i​n​g​…
			 */
			exporting: string
			/**
			 * C​l​e​a​r​ ​a​l​l​ ​f​i​l​t​e​r​s
			 */
			clearFilters: string
			/**
			 * D​i​s​m​i​s​s
			 */
			dismiss: string
		}
		/**
		 * C​l​e​a​r​ ​s​t​o​r​e​ ​f​i​l​t​e​r
		 */
		clearStoreFilter: string
		/**
		 * A​l​e​r​t​:​ ​{​d​a​y​s​}​ ​d​a​y​s
		 * @param {unknown} days
		 */
		alertDays: RequiredParams<'days'>
		/**
		 * D​a​y​s​ ​l​e​f​t
		 */
		daysLeft: string
		/**
		 * E​x​p​:​ ​{​d​a​t​e​}
		 * @param {unknown} date
		 */
		exp: RequiredParams<'date'>
		/**
		 * D​a​y​s
		 */
		days: string
		/**
		 * Q​t​y
		 */
		qty: string
		/**
		 * S​K​U
		 */
		sku: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n
		 */
		description: string
		/**
		 * S​t​o​r​e
		 */
		store: string
		/**
		 * L​o​c​a​t​i​o​n
		 */
		location: string
		/**
		 * E​x​p​i​r​y​ ​d​a​t​e
		 */
		expiryDate: string
		/**
		 * A​l​e​r​t​ ​d​a​y​s
		 */
		alertDaysBefore: string
		/**
		 * S​t​a​t​u​s
		 */
		status: string
		/**
		 * B​a​t​c​h
		 */
		batch: string
		/**
		 * P​r​o​d​u​c​t
		 */
		product: string
		/**
		 * U​n​i​t
		 */
		unit: string
		/**
		 * B​a​r​c​o​d​e
		 */
		barcode: string
		/**
		 * C​a​t​e​g​o​r​y
		 */
		category: string
		/**
		 * C​a​t​e​g​o​r​i​e​s
		 */
		categories: string
		/**
		 * A​c​t​i​v​e
		 */
		active: string
		/**
		 * A​r​c​h​i​v​e​d
		 */
		archived: string
		/**
		 * R​e​s​o​l​v​e​d
		 */
		resolved: string
		/**
		 * I​n​a​c​t​i​v​e
		 */
		inactive: string
		/**
		 * A​l​l​ ​l​o​c​a​t​i​o​n​s
		 */
		allLocations: string
		/**
		 * A​l​l​ ​s​t​o​r​e​s
		 */
		allStores: string
		/**
		 * A​l​l​ ​c​a​t​e​g​o​r​i​e​s
		 */
		allCategories: string
		/**
		 * A​l​l​ ​u​r​g​e​n​c​i​e​s
		 */
		allUrgencies: string
	}
	reports: {
		/**
		 * R​e​p​o​r​t​s
		 */
		pageTitle: string
		/**
		 * 1​.​ ​C​h​o​o​s​e​ ​a​ ​r​e​p​o​r​t
		 */
		chooseReport: string
		/**
		 * 2​.​ ​F​i​l​t​e​r​s
		 */
		configureFilters: string
		/**
		 * P​r​e​v​i​e​w​ ​r​e​p​o​r​t
		 */
		preview: string
		/**
		 * G​e​n​e​r​a​t​i​n​g​ ​p​r​e​v​i​e​w​…
		 */
		generating: string
		/**
		 * E​x​p​o​r​t​i​n​g​…
		 */
		exporting: string
		/**
		 * E​x​p​o​r​t​ ​P​D​F
		 */
		exportPdf: string
		/**
		 * ←​ ​E​d​i​t​ ​f​i​l​t​e​r​s
		 */
		editFilters: string
		/**
		 * P​r​e​v​i​e​w
		 */
		previewTitle: string
		actions: {
			/**
			 * ←​ ​E​d​i​t​ ​f​i​l​t​e​r​s
			 */
			editFilters: string
			/**
			 * P​r​e​v​i​e​w​ ​r​e​p​o​r​t
			 */
			preview: string
			/**
			 * G​e​n​e​r​a​t​i​n​g​ ​p​r​e​v​i​e​w​…
			 */
			generating: string
			/**
			 * E​x​p​o​r​t​i​n​g​…
			 */
			exporting: string
			/**
			 * E​x​p​o​r​t​ ​P​D​F
			 */
			exportPdf: string
		}
		emptyState: {
			/**
			 * N​o​ ​l​o​t​s​ ​m​a​t​c​h​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​r​e​p​o​r​t​ ​f​i​l​t​e​r​s​.
			 */
			noRowsMatch: string
			/**
			 * A​d​j​u​s​t​ ​t​h​e​ ​f​i​l​t​e​r​s​ ​a​b​o​v​e​ ​a​n​d​ ​r​u​n​ ​t​h​e​ ​p​r​e​v​i​e​w​ ​a​g​a​i​n​.
			 */
			adjustFilters: string
		}
		/**
		 * N​o​ ​l​o​t​s​ ​m​a​t​c​h​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​r​e​p​o​r​t​ ​f​i​l​t​e​r​s​.
		 */
		noRowsMatch: string
		/**
		 * A​d​j​u​s​t​ ​t​h​e​ ​f​i​l​t​e​r​s​ ​a​b​o​v​e​ ​a​n​d​ ​r​u​n​ ​t​h​e​ ​p​r​e​v​i​e​w​ ​a​g​a​i​n​.
		 */
		adjustFilters: string
		reportTypes: {
			/**
			 * I​n​ ​a​l​e​r​t​ ​w​i​n​d​o​w
			 */
			inAlertWindow: string
			/**
			 * L​o​t​s​ ​w​i​t​h​i​n​ ​t​h​e​i​r​ ​p​e​r​-​l​o​t​ ​a​l​e​r​t​ ​t​h​r​e​s​h​o​l​d​.
			 */
			inAlertWindowDesc: string
			/**
			 * E​x​p​i​r​e​d
			 */
			expired: string
			/**
			 * L​o​t​s​ ​p​a​s​t​ ​t​h​e​i​r​ ​e​x​p​i​r​y​ ​d​a​t​e​.
			 */
			expiredDesc: string
			/**
			 * N​e​x​t​ ​3​0​ ​d​a​y​s
			 */
			next30Days: string
			/**
			 * L​o​t​s​ ​e​x​p​i​r​i​n​g​ ​w​i​t​h​i​n​ ​t​h​e​ ​n​e​x​t​ ​3​0​ ​c​a​l​e​n​d​a​r​ ​d​a​y​s​.
			 */
			next30DaysDesc: string
			/**
			 * C​u​s​t​o​m
			 */
			custom: string
			/**
			 * B​u​i​l​d​ ​a​ ​r​e​p​o​r​t​ ​w​i​t​h​ ​a​r​b​i​t​r​a​r​y​ ​u​r​g​e​n​c​y​ ​/​ ​d​a​t​e​ ​/​ ​c​a​t​e​g​o​r​y​ ​f​i​l​t​e​r​s​.
			 */
			customDesc: string
		}
		fields: {
			/**
			 * S​t​o​r​e
			 */
			store: string
			/**
			 * L​o​c​a​t​i​o​n
			 */
			location: string
			/**
			 * C​a​t​e​g​o​r​y
			 */
			category: string
			/**
			 * U​r​g​e​n​c​y
			 */
			urgency: string
			/**
			 * D​a​t​e​ ​f​r​o​m
			 */
			dateFrom: string
			/**
			 * D​a​t​e​ ​t​o
			 */
			dateTo: string
			/**
			 * Y​Y​Y​Y​-​M​M​-​D​D
			 */
			datePlaceholder: string
		}
		urgencyOptions: {
			/**
			 * A​l​l​ ​u​r​g​e​n​c​i​e​s
			 */
			all: string
			/**
			 * E​x​p​i​r​e​d
			 */
			expired: string
			/**
			 * T​o​d​a​y
			 */
			today: string
			/**
			 * A​l​e​r​t​ ​w​i​n​d​o​w
			 */
			alertWindow: string
			/**
			 * N​e​x​t​ ​3​0​ ​d​a​y​s
			 */
			next30Days: string
			/**
			 * F​u​t​u​r​e
			 */
			future: string
		}
		table: {
			/**
			 * G​e​n​e​r​a​t​e​d​ ​a​t
			 */
			generatedAt: string
			/**
			 * R​o​w​s
			 */
			rows: string
			/**
			 * F​i​l​t​e​r​s
			 */
			filters: string
			/**
			 * (​n​o​ ​f​i​l​t​e​r​s​)
			 */
			noFilters: string
			/**
			 * S​K​U
			 */
			sku: string
			/**
			 * D​e​s​c​r​i​p​t​i​o​n
			 */
			description: string
			/**
			 * S​t​o​r​e​ ​/​ ​L​o​c​a​t​i​o​n
			 */
			storeLocation: string
			/**
			 * Q​t​y
			 */
			qty: string
			/**
			 * E​x​p​i​r​y
			 */
			expiry: string
			/**
			 * D​a​y​s
			 */
			days: string
			/**
			 * U​r​g​e​n​c​y
			 */
			urgency: string
			/**
			 * B​a​t​c​h
			 */
			batch: string
		}
		filterSummary: {
			/**
			 * s​t​o​r​e​=
			 */
			store: string
			/**
			 * l​o​c​a​t​i​o​n​=
			 */
			location: string
			/**
			 * c​a​t​e​g​o​r​i​e​s​ ​(​{​n​}​)
			 * @param {unknown} n
			 */
			categories: RequiredParams<'n'>
			/**
			 * c​a​t​e​g​o​r​i​e​s​=​{​n​}​ ​(​i​n​c​l​u​d​e​s​ ​u​n​c​a​t​e​g​o​r​i​z​e​d​)
			 * @param {unknown} n
			 */
			categoriesUnc: RequiredParams<'n'>
			/**
			 * u​r​g​e​n​c​y​=
			 */
			urgency: string
			/**
			 * f​r​o​m​=
			 */
			from: string
			/**
			 * t​o​=
			 */
			to: string
		}
		/**
		 * E​x​p​o​r​t​e​d​ ​{​r​o​w​s​}​ ​{​r​o​w​W​o​r​d​}​ ​a​c​r​o​s​s​ ​{​p​a​g​e​s​}​ ​p​a​g​e​{​p​a​g​e​s​W​o​r​d​}
		 * @param {unknown} pages
		 * @param {unknown} pagesWord
		 * @param {unknown} rows
		 * @param {unknown} rowWord
		 */
		exportSuccess: RequiredParams<'pages' | 'pagesWord' | 'rows' | 'rowWord'>
		/**
		 * p​a​g​e
		 */
		pageWord: string
		/**
		 * r​o​w
		 */
		rowWord: string
	}
	stores: {
		/**
		 * S​t​o​r​e​s
		 */
		pageTitle: string
		/**
		 * C​r​e​a​t​e​ ​S​t​o​r​e
		 */
		createStore: string
		/**
		 * E​d​i​t​ ​S​t​o​r​e
		 */
		editStore: string
		/**
		 * S​t​o​r​e​ ​n​a​m​e
		 */
		storeName: string
		/**
		 * C​o​d​e
		 */
		storeCode: string
		/**
		 * N​o​t​e​s
		 */
		storeNotes: string
		/**
		 * I​n​t​e​r​n​a​l​ ​L​o​c​a​t​i​o​n​s
		 */
		internalLocations: string
		/**
		 * C​r​e​a​t​e​ ​L​o​c​a​t​i​o​n
		 */
		createLocation: string
		/**
		 * E​d​i​t​ ​L​o​c​a​t​i​o​n
		 */
		editLocation: string
		/**
		 * L​o​c​a​t​i​o​n​ ​n​a​m​e
		 */
		locationName: string
		/**
		 * N​o​t​e​s
		 */
		locationNotes: string
		firstRun: {
			/**
			 * B​e​f​o​r​e​ ​y​o​u​ ​c​a​n​ ​t​r​a​c​k​ ​e​x​p​i​r​y​ ​l​o​t​s​,​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​s​t​o​r​e​.
			 */
			title: string
			/**
			 * C​r​e​a​t​e​ ​y​o​u​r​ ​f​i​r​s​t​ ​s​t​o​r​e
			 */
			subtitle: string
		}
		/**
		 * N​o​ ​s​t​o​r​e​s​ ​y​e​t
		 */
		noStores: string
		/**
		 * L​o​a​d​i​n​g​…
		 */
		loading: string
		/**
		 * S​e​l​e​c​t​ ​a​ ​s​t​o​r​e​ ​t​o​ ​m​a​n​a​g​e​ ​i​t​.
		 */
		selectToManage: string
		/**
		 * W​e​l​c​o​m​e​ ​t​o​ ​C​a​d​u​x​o​!
		 */
		welcomeTitle: string
		placeholders: {
			/**
			 * e​.​g​.​ ​M​a​i​n​ ​S​h​o​p
			 */
			storeName: string
			/**
			 * e​.​g​.​ ​M​S​-​0​0​1
			 */
			storeCode: string
			/**
			 * A​n​y​ ​n​o​t​e​s​…
			 */
			storeNotes: string
			/**
			 * e​.​g​.​ ​F​r​i​d​g​e​ ​A​,​ ​F​r​e​e​z​e​r​ ​1
			 */
			locationName: string
			/**
			 * O​p​t​i​o​n​a​l​ ​n​o​t​e​s​…
			 */
			locationNotes: string
		}
		/**
		 * N​o​ ​l​o​c​a​t​i​o​n​s​ ​y​e​t
		 */
		noLocations: string
		/**
		 * N​o​ ​l​o​c​a​t​i​o​n​s​ ​d​e​f​i​n​e​d​.​ ​A​d​d​ ​s​h​e​l​v​e​s​,​ ​f​r​i​d​g​e​s​,​ ​o​r​ ​s​e​c​t​i​o​n​s​.
		 */
		noLocationsHint: string
		/**
		 * S​e​l​e​c​t​e​d​ ​c​a​t​e​g​o​r​i​e​s
		 */
		selectedCategories: string
		/**
		 * R​e​m​o​v​e​ ​{​n​a​m​e​}
		 * @param {unknown} name
		 */
		removeCategory: RequiredParams<'name'>
		/**
		 * E​d​i​t
		 */
		edit: string
		/**
		 * S​e​l​e​c​t​ ​a​ ​s​t​o​r​e​ ​t​o​ ​m​a​n​a​g​e​ ​i​t​.
		 */
		noLocationSelectedHint: string
		/**
		 * S​e​l​e​c​t​ ​a​ ​s​t​o​r​e​ ​t​o​ ​m​a​n​a​g​e​ ​i​t​.
		 */
		noStoreSelectedHint: string
		/**
		 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​s​t​o​r​e​?​ ​T​h​i​s​ ​a​c​t​i​o​n​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
		 */
		confirmDeleteStore: string
		/**
		 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​l​o​c​a​t​i​o​n​?
		 */
		confirmDeleteLocation: string
		/**
		 * A​c​t​i​v​e
		 */
		active: string
		/**
		 * I​n​a​c​t​i​v​e
		 */
		inactive: string
		/**
		 * S​t​o​r​e​ ​n​a​m​e​ ​i​s​ ​r​e​q​u​i​r​e​d
		 */
		storeNameRequired: string
		/**
		 * S​t​o​r​e​ ​c​r​e​a​t​e​d
		 */
		storeCreated: string
		/**
		 * S​t​o​r​e​ ​u​p​d​a​t​e​d
		 */
		storeUpdated: string
		/**
		 * L​o​c​a​t​i​o​n​ ​c​r​e​a​t​e​d
		 */
		locationCreated: string
		/**
		 * L​o​c​a​t​i​o​n​ ​u​p​d​a​t​e​d
		 */
		locationUpdated: string
		/**
		 * A​d​d​ ​L​o​c​a​t​i​o​n
		 */
		addLocation: string
		/**
		 * L​o​c​a​t​i​o​n​ ​n​a​m​e​ ​i​s​ ​r​e​q​u​i​r​e​d
		 */
		locationRequired: string
		/**
		 * S​a​v​e​ ​C​h​a​n​g​e​s
		 */
		saveChanges: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
	}
	products: {
		/**
		 * P​r​o​d​u​c​t​s
		 */
		pageTitle: string
		/**
		 * C​r​e​a​t​e​ ​P​r​o​d​u​c​t
		 */
		createProduct: string
		/**
		 * E​d​i​t​ ​P​r​o​d​u​c​t
		 */
		editProduct: string
		/**
		 * S​K​U
		 */
		productSku: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n
		 */
		productDescription: string
		/**
		 * C​a​t​e​g​o​r​y
		 */
		productCategory: string
		/**
		 * U​n​i​t
		 */
		productUnit: string
		/**
		 * A​l​e​r​t​ ​d​a​y​s​ ​b​e​f​o​r​e​ ​e​x​p​i​r​y
		 */
		productAlertDays: string
		/**
		 * N​o​t​e​s
		 */
		productNotes: string
		/**
		 * B​a​r​c​o​d​e
		 */
		productBarcode: string
		/**
		 * A​d​d​ ​b​a​r​c​o​d​e
		 */
		addBarcode: string
		/**
		 * B​a​r​c​o​d​e​ ​a​d​d​e​d
		 */
		barcodeAdded: string
		/**
		 * B​a​r​c​o​d​e​ ​r​e​m​o​v​e​d
		 */
		barcodeRemoved: string
		/**
		 * N​o​ ​p​r​o​d​u​c​t​s​ ​y​e​t
		 */
		noProducts: string
		/**
		 * S​e​a​r​c​h​ ​b​y​ ​S​K​U​ ​o​r​ ​d​e​s​c​r​i​p​t​i​o​n​…
		 */
		searchPlaceholder: string
		/**
		 * S​e​a​r​c​h​ ​b​y​ ​s​c​a​n​ ​o​r​ ​S​K​U​…
		 */
		scanSearch: string
		/**
		 * N​o​ ​b​a​r​c​o​d​e
		 */
		noBarcode: string
		/**
		 * A​r​c​h​i​v​e​d​ ​p​r​o​d​u​c​t​s​ ​c​a​n​n​o​t​ ​r​e​c​e​i​v​e​ ​n​e​w​ ​b​a​r​c​o​d​e​s​.
		 */
		archivedProducts: string
		/**
		 * C​a​t​e​g​o​r​i​e​s
		 */
		categories: string
		/**
		 * N​o​ ​c​a​t​e​g​o​r​y
		 */
		noCategory: string
		/**
		 * S​e​l​e​c​t​ ​c​a​t​e​g​o​r​y
		 */
		selectCategory: string
		/**
		 * U​n​a​r​c​h​i​v​e
		 */
		unarchive: string
		/**
		 * A​r​c​h​i​v​e
		 */
		archive: string
		/**
		 * A​r​c​h​i​v​e​ ​p​r​o​d​u​c​t
		 */
		archiveProduct: string
		/**
		 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​a​r​c​h​i​v​e​ ​t​h​i​s​ ​p​r​o​d​u​c​t​?​ ​I​t​ ​w​i​l​l​ ​b​e​ ​h​i​d​d​e​n​ ​f​r​o​m​ ​t​h​e​ ​a​c​t​i​v​e​ ​l​i​s​t​.
		 */
		confirmArchive: string
		/**
		 * N​o​ ​p​r​o​d​u​c​t​s​ ​i​n​ ​t​h​i​s​ ​c​a​t​e​g​o​r​y​.
		 */
		noProductsInCategory: string
		/**
		 * N​o​ ​p​r​o​d​u​c​t​s​ ​m​a​t​c​h​ ​y​o​u​r​ ​s​e​a​r​c​h​.
		 */
		noProductsMatchSearch: string
		/**
		 * I​n​v​e​n​t​o​r​y
		 */
		inventory: string
		/**
		 * T​o​t​a​l
		 */
		total: string
		/**
		 * A​d​d
		 */
		add: string
		/**
		 * S​u​b​t​r​a​c​t
		 */
		subtract: string
		/**
		 * S​e​t​ ​c​o​u​n​t
		 */
		setCount: string
	}
	lotForm: {
		/**
		 * C​r​e​a​t​e​ ​e​x​p​i​r​y​ ​l​o​t
		 */
		createTitle: string
		/**
		 * E​d​i​t​ ​e​x​p​i​r​y​ ​l​o​t
		 */
		editTitle: string
		/**
		 * S​e​l​e​c​t​ ​p​r​o​d​u​c​t
		 */
		selectProduct: string
		/**
		 * S​e​l​e​c​t​ ​s​t​o​r​e
		 */
		selectStore: string
		/**
		 * S​e​l​e​c​t​ ​l​o​c​a​t​i​o​n
		 */
		selectLocation: string
		/**
		 * U​n​i​t
		 */
		selectUnit: string
		/**
		 * Q​u​a​n​t​i​t​y
		 */
		quantity: string
		/**
		 * Q​u​a​n​t​i​t​y​ ​*
		 */
		quantityStar: string
		/**
		 * A​c​t​u​a​l​ ​q​u​a​n​t​i​t​y​ ​i​n​ ​i​n​v​e​n​t​o​r​y​ ​*
		 */
		actualQuantity: string
		/**
		 * E​x​p​i​r​y​ ​d​a​t​e
		 */
		expiryDate: string
		/**
		 * N​o​t​i​f​i​c​a​t​i​o​n​ ​d​a​t​e
		 */
		notificationDate: string
		/**
		 * A​l​e​r​t​ ​d​a​y​s
		 */
		alertDays: string
		/**
		 * B​a​t​c​h​ ​c​o​d​e
		 */
		batchCode: string
		/**
		 * N​o​t​e​s
		 */
		notes: string
		/**
		 * S​a​v​e​ ​l​o​t
		 */
		save: string
		/**
		 * S​a​v​i​n​g​…
		 */
		saving: string
		/**
		 * S​e​l​e​c​t​ ​a​ ​l​o​c​a​t​i​o​n
		 */
		selectLocationPrompt: string
		/**
		 * N​o​ ​l​o​c​a​t​i​o​n​ ​s​e​l​e​c​t​e​d
		 */
		noLocationSelected: string
		/**
		 * A​ ​l​o​c​a​t​i​o​n​ ​i​s​ ​r​e​q​u​i​r​e​d​ ​t​o​ ​s​a​v​e​ ​t​h​i​s​ ​l​o​t​.
		 */
		requireLocationNote: string
		/**
		 * Y​Y​Y​Y​-​M​M​-​D​D
		 */
		dateFormat: string
	}
	lotMovements: {
		/**
		 * L​o​t​ ​m​o​v​e​m​e​n​t​s
		 */
		panelTitle: string
		/**
		 * M​o​v​e​m​e​n​t​ ​h​i​s​t​o​r​y
		 */
		history: string
		/**
		 * N​o​ ​m​o​v​e​m​e​n​t​s​ ​y​e​t​.
		 */
		noMovements: string
		/**
		 * M​o​v​e​ ​s​t​o​c​k
		 */
		moveStock: string
		/**
		 * R​e​g​i​s​t​e​r​ ​e​x​i​t
		 */
		registerExit: string
		/**
		 * A​d​j​u​s​t​ ​c​o​u​n​t
		 */
		adjustCount: string
		/**
		 * Q​u​a​n​t​i​t​y​ ​t​o​ ​a​d​d
		 */
		quantityToAdd: string
		/**
		 * Q​u​a​n​t​i​t​y​ ​t​o​ ​r​e​m​o​v​e
		 */
		quantityToRemove: string
		/**
		 * Q​u​a​n​t​i​t​y​ ​t​o​ ​s​e​t
		 */
		quantityToSet: string
		/**
		 * R​e​a​s​o​n
		 */
		reason: string
		reasons: {
			/**
			 * T​r​a​n​s​f​e​r
			 */
			transfer: string
			/**
			 * S​o​l​d
			 */
			sold: string
			/**
			 * C​o​n​s​u​m​e​d
			 */
			consumed: string
			/**
			 * D​i​s​c​a​r​d​e​d
			 */
			discarded: string
			/**
			 * D​o​n​a​t​e​d
			 */
			donated: string
			/**
			 * A​d​j​u​s​t​m​e​n​t
			 */
			adjustment: string
			/**
			 * E​x​p​i​r​e​d
			 */
			expired: string
			/**
			 * O​t​h​e​r
			 */
			other: string
		}
		resolution: {
			/**
			 * R​e​s​o​l​v​e​ ​q​u​a​n​t​i​t​y
			 */
			resolveQuantity: string
			/**
			 * C​o​n​s​u​m​e​d
			 */
			consumed: string
			/**
			 * S​o​l​d
			 */
			sold: string
			/**
			 * D​i​s​c​a​r​d​e​d
			 */
			discarded: string
			/**
			 * D​o​n​a​t​e​d
			 */
			donated: string
			/**
			 * O​t​h​e​r
			 */
			other: string
			/**
			 * R​e​s​o​l​u​t​i​o​n​ ​h​i​s​t​o​r​y
			 */
			resolutionHistory: string
			/**
			 * N​o​ ​r​e​s​o​l​u​t​i​o​n​ ​e​v​e​n​t​s​ ​y​e​t​.
			 */
			noHistory: string
			/**
			 * L​o​a​d​i​n​g​ ​h​i​s​t​o​r​y​…
			 */
			loadingHistory: string
		}
		/**
		 * C​u​r​r​e​n​t​ ​i​n​v​e​n​t​o​r​y​ ​a​t​ ​t​h​i​s​ ​l​o​c​a​t​i​o​n​:​ ​{​c​u​r​r​e​n​t​}
		 * @param {unknown} current
		 */
		currentInventory: RequiredParams<'current'>
		/**
		 * A​v​a​i​l​a​b​l​e​:​ ​{​a​v​a​i​l​a​b​l​e​}
		 * @param {unknown} available
		 */
		available: RequiredParams<'available'>
		/**
		 * W​i​l​l​ ​i​n​c​r​e​a​s​e​ ​i​n​v​e​n​t​o​r​y
		 */
		willIncrease: string
		/**
		 * W​i​l​l​ ​d​e​c​r​e​a​s​e​ ​i​n​v​e​n​t​o​r​y
		 */
		willDecrease: string
		/**
		 *  ​(​i​n​t​e​g​e​r​s​ ​o​n​l​y​)
		 */
		integerNote: string
	}
	calendar: {
		/**
		 * C​a​l​e​n​d​a​r
		 */
		pageTitle: string
		/**
		 * T​o​d​a​y
		 */
		today: string
		/**
		 * T​h​i​s​ ​w​e​e​k
		 */
		thisWeek: string
		/**
		 * T​h​i​s​ ​m​o​n​t​h
		 */
		thisMonth: string
		/**
		 * U​p​c​o​m​i​n​g
		 */
		upcoming: string
		/**
		 * E​x​p​i​r​i​n​g
		 */
		expiring: string
		/**
		 * N​o​ ​l​o​t​s​ ​e​x​p​i​r​i​n​g​ ​o​n​ ​t​h​i​s​ ​d​a​t​e​.
		 */
		noLotsOnDate: string
	}
	backupRestore: {
		/**
		 * B​a​c​k​u​p​ ​&​ ​R​e​s​t​o​r​e
		 */
		pageTitle: string
		/**
		 * E​x​p​o​r​t​ ​b​a​c​k​u​p
		 */
		exportSection: string
		/**
		 * C​r​e​a​t​e​s​ ​a​ ​f​u​l​l​ ​c​o​p​y​ ​o​f​ ​y​o​u​r​ ​d​a​t​a​b​a​s​e​ ​a​t​ ​a​ ​l​o​c​a​t​i​o​n​ ​y​o​u​ ​c​h​o​o​s​e​.​ ​T​h​e​ ​a​p​p​ ​r​e​m​a​i​n​s​ ​o​p​e​n​ ​a​n​d​ ​u​s​a​b​l​e​ ​d​u​r​i​n​g​ ​e​x​p​o​r​t​.
		 */
		exportDesc: string
		/**
		 * E​x​p​o​r​t​ ​b​a​c​k​u​p
		 */
		exportButton: string
		/**
		 * E​x​p​o​r​t​i​n​g​…
		 */
		exporting: string
		/**
		 * R​e​s​t​o​r​e​ ​f​r​o​m​ ​b​a​c​k​u​p
		 */
		restoreSection: string
		/**
		 * T​h​i​s​ ​i​s​ ​a​ ​d​e​s​t​r​u​c​t​i​v​e​ ​o​p​e​r​a​t​i​o​n​.
		 */
		restoreDesc: string
		/**
		 * M​a​k​e​ ​s​u​r​e​ ​y​o​u​ ​h​a​v​e​ ​a​n​ ​e​x​p​o​r​t​ ​o​f​ ​y​o​u​r​ ​c​u​r​r​e​n​t​ ​d​a​t​a​ ​b​e​f​o​r​e​ ​p​r​o​c​e​e​d​i​n​g​.
		 */
		restoreWarning: string
		/**
		 * A​r​e​ ​y​o​u​ ​s​u​r​e​?​ ​T​h​i​s​ ​w​i​l​l​ ​p​e​r​m​a​n​e​n​t​l​y​ ​r​e​p​l​a​c​e​ ​a​l​l​ ​c​u​r​r​e​n​t​ ​d​a​t​a​ ​w​i​t​h​ ​t​h​e​ ​b​a​c​k​u​p​.
		 */
		restoreConfirm: string
		/**
		 * R​e​s​t​o​r​e​ ​f​r​o​m​ ​b​a​c​k​u​p
		 */
		restoreButton: string
		/**
		 * R​e​s​t​o​r​i​n​g​…
		 */
		restoring: string
		/**
		 * A​b​o​u​t​ ​b​a​c​k​u​p​s
		 */
		aboutSection: string
		/**
		 * W​h​a​t​ ​i​s​ ​i​n​c​l​u​d​e​d​?
		 */
		includesQ: string
		/**
		 * F​u​l​l​ ​d​a​t​a​b​a​s​e​ ​c​o​p​y​ ​i​n​c​l​u​d​i​n​g​ ​a​l​l​ ​s​t​o​r​e​s​,​ ​p​r​o​d​u​c​t​s​,​ ​e​x​p​i​r​y​ ​l​o​t​s​,​ ​c​a​t​e​g​o​r​i​e​s​,​ ​s​e​t​t​i​n​g​s​,​ ​a​n​d​ ​h​i​s​t​o​r​y​.
		 */
		includesA: string
		/**
		 * H​o​w​ ​o​f​t​e​n​ ​s​h​o​u​l​d​ ​I​ ​b​a​c​k​ ​u​p​?
		 */
		howOftenQ: string
		/**
		 * R​e​g​u​l​a​r​ ​b​a​c​k​u​p​s​ ​a​r​e​ ​r​e​c​o​m​m​e​n​d​e​d​ ​b​e​f​o​r​e​ ​m​a​j​o​r​ ​c​h​a​n​g​e​s​ ​l​i​k​e​ ​C​S​V​ ​i​m​p​o​r​t​s​ ​o​r​ ​b​u​l​k​ ​l​o​t​ ​o​p​e​r​a​t​i​o​n​s​.
		 */
		howOftenA: string
		/**
		 * W​h​e​r​e​ ​s​h​o​u​l​d​ ​I​ ​s​a​v​e​ ​b​a​c​k​u​p​s​?
		 */
		whereQ: string
		/**
		 * A​n​y​ ​l​o​c​a​t​i​o​n​ ​y​o​u​ ​c​h​o​o​s​e​ ​—​ ​e​x​t​e​r​n​a​l​ ​d​r​i​v​e​,​ ​c​l​o​u​d​ ​f​o​l​d​e​r​,​ ​o​r​ ​l​o​c​a​l​ ​d​i​r​e​c​t​o​r​y​.​ ​S​t​a​n​d​a​r​d​ ​S​Q​L​i​t​e​ ​f​i​l​e​s​ ​c​a​n​ ​b​e​ ​o​p​e​n​e​d​ ​w​i​t​h​ ​m​o​s​t​ ​d​a​t​a​b​a​s​e​ ​t​o​o​l​s​.
		 */
		whereA: string
		/**
		 * C​u​r​r​e​n​t​ ​d​a​t​a​b​a​s​e​ ​l​o​c​a​t​i​o​n
		 */
		locationQ: string
		/**
		 * T​h​e​ ​a​c​t​i​v​e​ ​d​a​t​a​b​a​s​e​ ​i​s​ ​s​t​o​r​e​d​ ​i​n​ ​t​h​e​ ​a​p​p​'​s​ ​l​o​c​a​l​ ​d​a​t​a​ ​d​i​r​e​c​t​o​r​y​.​ ​T​h​e​ ​b​a​c​k​u​p​ ​e​x​p​o​r​t​ ​l​e​t​s​ ​y​o​u​ ​c​h​o​o​s​e​ ​w​h​e​r​e​ ​t​o​ ​s​a​v​e​ ​y​o​u​r​ ​c​o​p​y​.
		 */
		locationA: string
	}
	csvImport: {
		/**
		 * I​m​p​o​r​t​ ​P​r​o​d​u​c​t​s​ ​f​r​o​m​ ​C​S​V
		 */
		pageTitle: string
		/**
		 * S​e​l​e​c​t​ ​C​S​V​ ​f​i​l​e
		 */
		selectFile: string
		/**
		 * C​h​o​o​s​e​ ​a​ ​C​S​V​ ​f​i​l​e​ ​t​o​ ​i​m​p​o​r​t​ ​p​r​o​d​u​c​t​s
		 */
		selectFileDesc: string
		/**
		 * E​x​p​e​c​t​e​d​ ​c​o​l​u​m​n​s
		 */
		expectedColumns: string
		/**
		 * T​i​p​:
		 */
		tip: string
		/**
		 * C​o​l​u​m​n​ ​h​e​a​d​e​r​s​ ​a​r​e​ ​a​u​t​o​-​d​e​t​e​c​t​e​d​.​ ​C​o​m​m​o​n​ ​a​l​i​a​s​e​s​ ​a​r​e​ ​a​c​c​e​p​t​e​d​.
		 */
		tipText: string
		/**
		 * M​a​p​ ​C​S​V​ ​C​o​l​u​m​n​s
		 */
		mapColumns: string
		/**
		 * F​i​e​l​d
		 */
		field: string
		/**
		 * C​o​l​u​m​n
		 */
		column: string
		/**
		 * P​r​e​v​i​e​w
		 */
		preview: string
		/**
		 * R​e​q​u​i​r​e​d
		 */
		required: string
		/**
		 * I​m​p​o​r​t​ ​P​r​e​v​i​e​w
		 */
		importPreview: string
		/**
		 * T​o​t​a​l​ ​r​o​w​s
		 */
		totalRows: string
		/**
		 * V​a​l​i​d
		 */
		valid: string
		duplicates: {
			/**
			 * D​u​p​l​i​c​a​t​e​ ​S​K​U
			 */
			sku: string
			/**
			 * D​u​p​l​i​c​a​t​e​ ​b​a​r​c​o​d​e
			 */
			barcode: string
		}
		/**
		 * M​i​s​s​i​n​g​ ​r​e​q​u​i​r​e​d
		 */
		missing: string
		/**
		 * C​o​n​f​l​i​c​t​ ​S​t​r​a​t​e​g​y
		 */
		conflictStrategy: string
		/**
		 * R​o​w​ ​D​e​t​a​i​l​s
		 */
		rowDetails: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n
		 */
		description: string
		/**
		 * S​t​a​t​u​s
		 */
		status: string
		/**
		 * D​e​t​a​i​l
		 */
		detail: string
		/**
		 * I​m​p​o​r​t​ ​C​o​m​p​l​e​t​e
		 */
		importComplete: string
		/**
		 * C​r​e​a​t​e​d
		 */
		created: string
		/**
		 * U​p​d​a​t​e​d
		 */
		updated: string
		/**
		 * S​k​i​p​p​e​d
		 */
		skipped: string
		/**
		 * I​n​v​a​l​i​d
		 */
		invalid: string
		/**
		 * I​m​p​o​r​t​ ​L​o​g
		 */
		importLog: string
		/**
		 * I​m​p​o​r​t
		 */
		importButton: string
		/**
		 * I​m​p​o​r​t​i​n​g​…
		 */
		importing: string
		conflictOptions: {
			/**
			 * S​k​i​p​ ​e​x​i​s​t​i​n​g
			 */
			skip: string
			/**
			 * O​v​e​r​w​r​i​t​e​ ​e​x​i​s​t​i​n​g
			 */
			overwrite: string
			/**
			 * S​k​i​p​ ​d​u​p​l​i​c​a​t​e​s
			 */
			skipDuplicates: string
		}
	}
	unitReview: {
		/**
		 * U​n​i​t​ ​R​e​v​i​e​w
		 */
		pageTitle: string
		/**
		 * {​c​o​u​n​t​}​ ​p​r​o​d​u​c​t​{​s​}​ ​u​s​e​ ​n​o​n​-​s​t​a​n​d​a​r​d​ ​u​n​i​t​s​.
		 * @param {unknown} count
		 * @param {unknown} s
		 */
		unitCount: RequiredParams<'count' | 's'>
		/**
		 * R​e​v​i​e​w​ ​u​n​i​t
		 */
		reviewUnit: string
		/**
		 * K​e​e​p
		 */
		keep: string
		/**
		 * K​e​e​p​ ​a​s​ ​c​u​s​t​o​m
		 */
		keepAsCustom: string
		/**
		 * M​a​p​ ​t​o​ ​s​t​a​n​d​a​r​d
		 */
		mapToStandard: string
		/**
		 * P​r​e​s​e​t​ ​u​n​i​t​s​:
		 */
		presetUnits: string
		/**
		 * C​u​s​t​o​m​ ​u​n​i​t​s​:
		 */
		customUnits: string
	}
	scan: {
		/**
		 * S​e​a​r​c​h​ ​b​y​ ​s​c​a​n​ ​o​r​ ​S​K​U​…
		 */
		placeholder: string
		/**
		 * S​c​a​n​ ​b​a​r​c​o​d​e​ ​o​r​ ​e​n​t​e​r​ ​S​K​U
		 */
		ariaLabel: string
		/**
		 * P​r​e​s​s​ ​E​n​t​e​r​ ​t​o​ ​s​e​a​r​c​h
		 */
		title: string
		/**
		 * N​o​ ​p​r​o​d​u​c​t​ ​f​o​u​n​d​ ​f​o​r​ ​t​h​i​s​ ​b​a​r​c​o​d​e​.
		 */
		noMatch: string
		/**
		 * S​e​a​r​c​h​ ​f​a​i​l​e​d​:​ ​{​m​s​g​}
		 * @param {unknown} msg
		 */
		searchError: RequiredParams<'msg'>
	}
	categoryPicker: {
		/**
		 * F​i​l​t​e​r​ ​b​y​ ​c​a​t​e​g​o​r​y​…
		 */
		placeholder: string
		/**
		 * S​e​a​r​c​h​ ​c​a​t​e​g​o​r​i​e​s​…
		 */
		searchPlaceholder: string
		/**
		 * S​e​l​e​c​t​e​d​ ​c​a​t​e​g​o​r​i​e​s
		 */
		selectedCategories: string
		/**
		 * R​e​m​o​v​e​ ​{​n​a​m​e​}
		 * @param {unknown} name
		 */
		removeCategory: RequiredParams<'name'>
		/**
		 * C​l​e​a​r​ ​a​l​l
		 */
		clearAll: string
		/**
		 * C​l​e​a​r​ ​a​l​l​ ​s​e​l​e​c​t​e​d​ ​c​a​t​e​g​o​r​i​e​s
		 */
		clearAllAria: string
		/**
		 * S​e​a​r​c​h​ ​c​a​t​e​g​o​r​i​e​s
		 */
		searchAria: string
		/**
		 * C​l​o​s​e
		 */
		closeAria: string
		/**
		 * S​e​a​r​c​h​i​n​g​…
		 */
		searching: string
		/**
		 * N​o​ ​c​a​t​e​g​o​r​i​e​s​ ​y​e​t
		 */
		noCategories: string
		/**
		 * C​r​e​a​t​i​n​g​…
		 */
		creating: string
		/**
		 * U​n​c​a​t​e​g​o​r​i​z​e​d
		 */
		uncategorized: string
		/**
		 * N​o​ ​c​a​t​e​g​o​r​y
		 */
		noCategory: string
		/**
		 * "​{​n​a​m​e​}​"​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
		 * @param {unknown} name
		 */
		alreadyExists: RequiredParams<'name'>
		/**
		 * C​r​e​a​t​e​ ​"​{​n​a​m​e​}​"
		 * @param {unknown} name
		 */
		createOption: RequiredParams<'name'>
	}
	notification: {
		/**
		 * ⚠​️​ ​E​x​p​i​r​y​ ​a​l​e​r​t​:​ 
		 */
		titlePrefix: string
		/**
		 * {​q​t​y​}​ ​e​x​p​i​r​e​s​ ​o​n​ ​{​e​x​p​i​r​y​_​d​a​t​e​}​ ​·​ ​{​l​o​c​a​t​i​o​n​}
		 * @param {unknown} expiry_date
		 * @param {unknown} location
		 * @param {unknown} qty
		 */
		bodyTemplate: RequiredParams<'expiry_date' | 'location' | 'qty'>
	}
	pdf: {
		/**
		 * C​a​d​u​x​o​ ​R​e​p​o​r​t
		 */
		documentTitle: string
		/**
		 * G​e​n​e​r​a​t​e​d​ ​a​t
		 */
		generatedAt: string
		/**
		 * R​o​w​s
		 */
		rows: string
		/**
		 * F​i​l​t​e​r​s
		 */
		filters: string
		/**
		 * F​i​l​t​e​r​s​:
		 */
		filtersPrefix: string
		/**
		 * N​o​ ​r​o​w​s​ ​m​a​t​c​h​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​r​e​p​o​r​t​ ​f​i​l​t​e​r​s​.
		 */
		emptyNotice: string
		/**
		 * S​K​U
		 */
		columnSku: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n
		 */
		columnDescription: string
		/**
		 * S​t​o​r​e​ ​/​ ​L​o​c​a​t​i​o​n
		 */
		columnStoreLocation: string
		/**
		 * Q​t​y
		 */
		columnQty: string
		/**
		 * E​x​p​i​r​y
		 */
		columnExpiry: string
		/**
		 * D​a​y​s
		 */
		columnDays: string
		/**
		 * A​l​e​r​t
		 */
		columnAlert: string
		/**
		 * B​a​t​c​h
		 */
		columnBatch: string
		/**
		 * C​a​d​u​x​o​ ​·​ ​E​x​p​i​r​y​ ​T​r​a​c​k​e​r
		 */
		brand: string
		/**
		 * P​a​g​e​ ​{​n​}​ ​o​f​ ​{​m​}
		 * @param {unknown} m
		 * @param {unknown} n
		 */
		pageOf: RequiredParams<'m' | 'n'>
		/**
		 * {​n​}​ ​a​g​o
		 * @param {unknown} n
		 */
		daysAgo: RequiredParams<'n'>
	}
	errors: {
		/**
		 * A​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
		 */
		generic: string
		/**
		 * C​o​u​l​d​ ​n​o​t​ ​l​o​a​d​ ​d​a​t​a​.
		 */
		loadFailed: string
		/**
		 * C​o​u​l​d​ ​n​o​t​ ​s​a​v​e​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
		 */
		saveFailed: string
		/**
		 * N​o​t​ ​f​o​u​n​d​.
		 */
		notFound: string
		/**
		 * I​n​v​a​l​i​d​ ​{​l​a​b​e​l​}​ ​f​o​r​m​a​t​:​ ​`​{​v​a​l​u​e​}​`​ ​(​e​x​p​e​c​t​e​d​ ​Y​Y​Y​Y​-​M​M​-​D​D​)
		 * @param {unknown} label
		 * @param {unknown} value
		 */
		invalidDateFormat: RequiredParams<'label' | 'value'>
		/**
		 * U​s​e​ ​Y​Y​Y​Y​-​M​M​-​D​D
		 */
		dateUseIsoFormat: string
		/**
		 * Y​e​a​r​ ​m​u​s​t​ ​b​e​ ​1​9​0​0​–​2​1​0​0
		 */
		dateYearRange: string
		/**
		 * T​h​i​s​ ​f​i​e​l​d​ ​i​s​ ​r​e​q​u​i​r​e​d
		 */
		dateFieldRequired: string
		/**
		 * I​n​v​a​l​i​d​ ​d​a​t​e
		 */
		dateInvalid: string
	}
}

export type TranslationFunctions = {
	nav: {
		/**
		 * Dashboard
		 */
		dashboard: () => LocalizedString
		/**
		 * Stores
		 */
		stores: () => LocalizedString
		/**
		 * Products
		 */
		products: () => LocalizedString
		/**
		 * Calendar
		 */
		calendar: () => LocalizedString
		/**
		 * Reports
		 */
		reports: () => LocalizedString
		/**
		 * Import
		 */
		'import': () => LocalizedString
		/**
		 * Backup
		 */
		backup: () => LocalizedString
		/**
		 * Configuration
		 */
		settings: () => LocalizedString
	}
	common: {
		/**
		 * Loading…
		 */
		loading: () => LocalizedString
		/**
		 * Loading…
		 */
		loadingWithDots: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Save
		 */
		saveAction: () => LocalizedString
		/**
		 * Saving…
		 */
		saving: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * Archive
		 */
		archive: () => LocalizedString
		/**
		 * Edit
		 */
		edit: () => LocalizedString
		/**
		 * Create
		 */
		create: () => LocalizedString
		/**
		 * Creating…
		 */
		creating: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * Back
		 */
		back: () => LocalizedString
		/**
		 * Confirm
		 */
		confirm: () => LocalizedString
		/**
		 * Dismiss
		 */
		dismiss: () => LocalizedString
		/**
		 * Yes
		 */
		yes: () => LocalizedString
		/**
		 * No
		 */
		no: () => LocalizedString
		/**
		 * Error
		 */
		error: () => LocalizedString
		/**
		 * Success
		 */
		success: () => LocalizedString
		/**
		 * Loading lots…
		 */
		loadingLots: () => LocalizedString
		/**
		 * Loading dashboard…
		 */
		loadingDashboard: () => LocalizedString
		/**
		 * Loading movements…
		 */
		loadingMovements: () => LocalizedString
		/**
		 * Loading history…
		 */
		loadingHistory: () => LocalizedString
		/**
		 * Failed to load: {msg}
		 */
		failedToLoad: (arg: { msg: unknown }) => LocalizedString
		/**
		 * Failed to load lots: {msg}
		 */
		failedToLoadLots: (arg: { msg: unknown }) => LocalizedString
		/**
		 * Loading failed: {msg}
		 */
		loadingFailed: (arg: { msg: unknown }) => LocalizedString
		/**
		 * Required
		 */
		required: () => LocalizedString
		/**
		 * Optional
		 */
		optional: () => LocalizedString
		/**
		 * Actions
		 */
		actions: () => LocalizedString
		/**
		 * Filter
		 */
		filter: () => LocalizedString
		/**
		 * Filters
		 */
		filters: () => LocalizedString
		/**
		 * No results
		 */
		noResults: () => LocalizedString
		/**
		 * No results found.
		 */
		noResultsFound: () => LocalizedString
		/**
		 * Confirm deletion
		 */
		confirmDelete: () => LocalizedString
		/**
		 * Confirm archive
		 */
		confirmArchive: () => LocalizedString
		/**
		 * Confirm restore
		 */
		confirmRestore: () => LocalizedString
		/**
		 * No location
		 */
		noLocation: () => LocalizedString
	}
	configuration: {
		/**
		 * Configuration
		 */
		pageTitle: () => LocalizedString
		section: {
			/**
			 * Lots
			 */
			lots: () => LocalizedString
			/**
			 * Backup
			 */
			backup: () => LocalizedString
		}
		locationRequired: {
			/**
			 * Require initial location when creating a lot
			 */
			label: () => LocalizedString
			/**
			 * When enabled, the lot-creation form requires a location to be selected. When disabled, lots may be created without a location (a default location is assigned).
			 */
			description: () => LocalizedString
		}
		language: {
			/**
			 * Language
			 */
			sectionTitle: () => LocalizedString
			/**
			 * Interface language
			 */
			label: () => LocalizedString
			/**
			 * Detected: English
			 */
			detectedHintEn: () => LocalizedString
			/**
			 * Detected: Spanish
			 */
			detectedHintEs: () => LocalizedString
			/**
			 * Saving…
			 */
			saving: () => LocalizedString
			/**
			 * Could not load settings: 
			 */
			loadErrorPrefix: () => LocalizedString
			/**
			 * Could not save setting: 
			 */
			saveErrorPrefix: () => LocalizedString
			/**
			 * English
			 */
			english: () => LocalizedString
			/**
			 * Español
			 */
			spanish: () => LocalizedString
		}
	}
	dashboard: {
		/**
		 * Dashboard
		 */
		pageTitle: () => LocalizedString
		presets: {
			/**
			 * All
			 */
			all: () => LocalizedString
			/**
			 * Alert window
			 */
			alertWindow: () => LocalizedString
			/**
			 * Today
			 */
			today: () => LocalizedString
			/**
			 * Next 7 days
			 */
			next7Days: () => LocalizedString
			/**
			 * Next 30 days
			 */
			next30Days: () => LocalizedString
			/**
			 * Future
			 */
			future: () => LocalizedString
		}
		banners: {
			/**
			 * Some product units could not be mapped to standard units. {count} product{s} need{s} review.
			 */
			unitAudit: (arg: { count: unknown, s: unknown }) => LocalizedString
			/**
			 * Unit review dismissed.
			 */
			unitAuditDismissed: () => LocalizedString
		}
		emptyState: {
			/**
			 * No lots match this filter
			 */
			title: () => LocalizedString
			/**
			 * Adjust your filters or create some expiry lots.
			 */
			subtitle: () => LocalizedString
			/**
			 * This product has no expiry lots yet.
			 */
			noExpiryLots: () => LocalizedString
			/**
			 * {n} lot
			 */
			lots: (arg: { n: unknown }) => LocalizedString
		}
		unitReviewPanel: {
			/**
			 * Unit review
			 */
			unitReview: () => LocalizedString
			/**
			 * Some products use non-standard units. Review to improve data consistency.
			 */
			unitReviewDesc: () => LocalizedString
			/**
			 * Dismiss
			 */
			dismiss: () => LocalizedString
			/**
			 * Available: {available}{isIntegerNote}
			 */
			available: (arg: { available: unknown, isIntegerNote: unknown }) => LocalizedString
			/**
			 * Current inventory at this location: {current}{isIntegerNote}
			 */
			currentInventory: (arg: { current: unknown, isIntegerNote: unknown }) => LocalizedString
			/**
			 * Will increase inventory
			 */
			willIncrease: () => LocalizedString
			/**
			 * Will decrease inventory
			 */
			willDecrease: () => LocalizedString
			/**
			 *  (integers only)
			 */
			integerNote: () => LocalizedString
		}
		urgency: {
			/**
			 * Expired
			 */
			expired: () => LocalizedString
			/**
			 * Today
			 */
			today: () => LocalizedString
			/**
			 * Alert
			 */
			alertWindow: () => LocalizedString
			/**
			 * Next 30d
			 */
			next30Days: () => LocalizedString
			/**
			 * Future
			 */
			future: () => LocalizedString
		}
		/**
		 * Urgency
		 */
		urgencyLabel: () => LocalizedString
		/**
		 * Lot Detail
		 */
		lotDetail: () => LocalizedString
		/**
		 * Detail
		 */
		detail: () => LocalizedString
		/**
		 * Lot ID
		 */
		lotId: () => LocalizedString
		/**
		 * View product and lot movements
		 */
		viewProductAndMovements: () => LocalizedString
		/**
		 * Expiry lots
		 */
		expiryLots: () => LocalizedString
		/**
		 * Loading…
		 */
		loading: () => LocalizedString
		urgencyCard: {
			/**
			 * Expired
			 */
			expired: () => LocalizedString
			/**
			 * Today
			 */
			today: () => LocalizedString
			/**
			 * Alert window
			 */
			alertWindow: () => LocalizedString
			/**
			 * Next 30 days
			 */
			next30Days: () => LocalizedString
		}
		actions: {
			/**
			 * Export CSV
			 */
			exportCsv: () => LocalizedString
			/**
			 * Export the current dashboard report to a CSV file
			 */
			exportCsvTitle: () => LocalizedString
			/**
			 * Exporting…
			 */
			exporting: () => LocalizedString
			/**
			 * Clear all filters
			 */
			clearFilters: () => LocalizedString
			/**
			 * Dismiss
			 */
			dismiss: () => LocalizedString
		}
		/**
		 * Clear store filter
		 */
		clearStoreFilter: () => LocalizedString
		/**
		 * Alert: {days} days
		 */
		alertDays: (arg: { days: unknown }) => LocalizedString
		/**
		 * Days left
		 */
		daysLeft: () => LocalizedString
		/**
		 * Exp: {date}
		 */
		exp: (arg: { date: unknown }) => LocalizedString
		/**
		 * Days
		 */
		days: () => LocalizedString
		/**
		 * Qty
		 */
		qty: () => LocalizedString
		/**
		 * SKU
		 */
		sku: () => LocalizedString
		/**
		 * Description
		 */
		description: () => LocalizedString
		/**
		 * Store
		 */
		store: () => LocalizedString
		/**
		 * Location
		 */
		location: () => LocalizedString
		/**
		 * Expiry date
		 */
		expiryDate: () => LocalizedString
		/**
		 * Alert days
		 */
		alertDaysBefore: () => LocalizedString
		/**
		 * Status
		 */
		status: () => LocalizedString
		/**
		 * Batch
		 */
		batch: () => LocalizedString
		/**
		 * Product
		 */
		product: () => LocalizedString
		/**
		 * Unit
		 */
		unit: () => LocalizedString
		/**
		 * Barcode
		 */
		barcode: () => LocalizedString
		/**
		 * Category
		 */
		category: () => LocalizedString
		/**
		 * Categories
		 */
		categories: () => LocalizedString
		/**
		 * Active
		 */
		active: () => LocalizedString
		/**
		 * Archived
		 */
		archived: () => LocalizedString
		/**
		 * Resolved
		 */
		resolved: () => LocalizedString
		/**
		 * Inactive
		 */
		inactive: () => LocalizedString
		/**
		 * All locations
		 */
		allLocations: () => LocalizedString
		/**
		 * All stores
		 */
		allStores: () => LocalizedString
		/**
		 * All categories
		 */
		allCategories: () => LocalizedString
		/**
		 * All urgencies
		 */
		allUrgencies: () => LocalizedString
	}
	reports: {
		/**
		 * Reports
		 */
		pageTitle: () => LocalizedString
		/**
		 * 1. Choose a report
		 */
		chooseReport: () => LocalizedString
		/**
		 * 2. Filters
		 */
		configureFilters: () => LocalizedString
		/**
		 * Preview report
		 */
		preview: () => LocalizedString
		/**
		 * Generating preview…
		 */
		generating: () => LocalizedString
		/**
		 * Exporting…
		 */
		exporting: () => LocalizedString
		/**
		 * Export PDF
		 */
		exportPdf: () => LocalizedString
		/**
		 * ← Edit filters
		 */
		editFilters: () => LocalizedString
		/**
		 * Preview
		 */
		previewTitle: () => LocalizedString
		actions: {
			/**
			 * ← Edit filters
			 */
			editFilters: () => LocalizedString
			/**
			 * Preview report
			 */
			preview: () => LocalizedString
			/**
			 * Generating preview…
			 */
			generating: () => LocalizedString
			/**
			 * Exporting…
			 */
			exporting: () => LocalizedString
			/**
			 * Export PDF
			 */
			exportPdf: () => LocalizedString
		}
		emptyState: {
			/**
			 * No lots match the current report filters.
			 */
			noRowsMatch: () => LocalizedString
			/**
			 * Adjust the filters above and run the preview again.
			 */
			adjustFilters: () => LocalizedString
		}
		/**
		 * No lots match the current report filters.
		 */
		noRowsMatch: () => LocalizedString
		/**
		 * Adjust the filters above and run the preview again.
		 */
		adjustFilters: () => LocalizedString
		reportTypes: {
			/**
			 * In alert window
			 */
			inAlertWindow: () => LocalizedString
			/**
			 * Lots within their per-lot alert threshold.
			 */
			inAlertWindowDesc: () => LocalizedString
			/**
			 * Expired
			 */
			expired: () => LocalizedString
			/**
			 * Lots past their expiry date.
			 */
			expiredDesc: () => LocalizedString
			/**
			 * Next 30 days
			 */
			next30Days: () => LocalizedString
			/**
			 * Lots expiring within the next 30 calendar days.
			 */
			next30DaysDesc: () => LocalizedString
			/**
			 * Custom
			 */
			custom: () => LocalizedString
			/**
			 * Build a report with arbitrary urgency / date / category filters.
			 */
			customDesc: () => LocalizedString
		}
		fields: {
			/**
			 * Store
			 */
			store: () => LocalizedString
			/**
			 * Location
			 */
			location: () => LocalizedString
			/**
			 * Category
			 */
			category: () => LocalizedString
			/**
			 * Urgency
			 */
			urgency: () => LocalizedString
			/**
			 * Date from
			 */
			dateFrom: () => LocalizedString
			/**
			 * Date to
			 */
			dateTo: () => LocalizedString
			/**
			 * YYYY-MM-DD
			 */
			datePlaceholder: () => LocalizedString
		}
		urgencyOptions: {
			/**
			 * All urgencies
			 */
			all: () => LocalizedString
			/**
			 * Expired
			 */
			expired: () => LocalizedString
			/**
			 * Today
			 */
			today: () => LocalizedString
			/**
			 * Alert window
			 */
			alertWindow: () => LocalizedString
			/**
			 * Next 30 days
			 */
			next30Days: () => LocalizedString
			/**
			 * Future
			 */
			future: () => LocalizedString
		}
		table: {
			/**
			 * Generated at
			 */
			generatedAt: () => LocalizedString
			/**
			 * Rows
			 */
			rows: () => LocalizedString
			/**
			 * Filters
			 */
			filters: () => LocalizedString
			/**
			 * (no filters)
			 */
			noFilters: () => LocalizedString
			/**
			 * SKU
			 */
			sku: () => LocalizedString
			/**
			 * Description
			 */
			description: () => LocalizedString
			/**
			 * Store / Location
			 */
			storeLocation: () => LocalizedString
			/**
			 * Qty
			 */
			qty: () => LocalizedString
			/**
			 * Expiry
			 */
			expiry: () => LocalizedString
			/**
			 * Days
			 */
			days: () => LocalizedString
			/**
			 * Urgency
			 */
			urgency: () => LocalizedString
			/**
			 * Batch
			 */
			batch: () => LocalizedString
		}
		filterSummary: {
			/**
			 * store=
			 */
			store: () => LocalizedString
			/**
			 * location=
			 */
			location: () => LocalizedString
			/**
			 * categories ({n})
			 */
			categories: (arg: { n: unknown }) => LocalizedString
			/**
			 * categories={n} (includes uncategorized)
			 */
			categoriesUnc: (arg: { n: unknown }) => LocalizedString
			/**
			 * urgency=
			 */
			urgency: () => LocalizedString
			/**
			 * from=
			 */
			from: () => LocalizedString
			/**
			 * to=
			 */
			to: () => LocalizedString
		}
		/**
		 * Exported {rows} {rowWord} across {pages} page{pagesWord}
		 */
		exportSuccess: (arg: { pages: unknown, pagesWord: unknown, rows: unknown, rowWord: unknown }) => LocalizedString
		/**
		 * page
		 */
		pageWord: () => LocalizedString
		/**
		 * row
		 */
		rowWord: () => LocalizedString
	}
	stores: {
		/**
		 * Stores
		 */
		pageTitle: () => LocalizedString
		/**
		 * Create Store
		 */
		createStore: () => LocalizedString
		/**
		 * Edit Store
		 */
		editStore: () => LocalizedString
		/**
		 * Store name
		 */
		storeName: () => LocalizedString
		/**
		 * Code
		 */
		storeCode: () => LocalizedString
		/**
		 * Notes
		 */
		storeNotes: () => LocalizedString
		/**
		 * Internal Locations
		 */
		internalLocations: () => LocalizedString
		/**
		 * Create Location
		 */
		createLocation: () => LocalizedString
		/**
		 * Edit Location
		 */
		editLocation: () => LocalizedString
		/**
		 * Location name
		 */
		locationName: () => LocalizedString
		/**
		 * Notes
		 */
		locationNotes: () => LocalizedString
		firstRun: {
			/**
			 * Before you can track expiry lots, you need to create at least one store.
			 */
			title: () => LocalizedString
			/**
			 * Create your first store
			 */
			subtitle: () => LocalizedString
		}
		/**
		 * No stores yet
		 */
		noStores: () => LocalizedString
		/**
		 * Loading…
		 */
		loading: () => LocalizedString
		/**
		 * Select a store to manage it.
		 */
		selectToManage: () => LocalizedString
		/**
		 * Welcome to Caduxo!
		 */
		welcomeTitle: () => LocalizedString
		placeholders: {
			/**
			 * e.g. Main Shop
			 */
			storeName: () => LocalizedString
			/**
			 * e.g. MS-001
			 */
			storeCode: () => LocalizedString
			/**
			 * Any notes…
			 */
			storeNotes: () => LocalizedString
			/**
			 * e.g. Fridge A, Freezer 1
			 */
			locationName: () => LocalizedString
			/**
			 * Optional notes…
			 */
			locationNotes: () => LocalizedString
		}
		/**
		 * No locations yet
		 */
		noLocations: () => LocalizedString
		/**
		 * No locations defined. Add shelves, fridges, or sections.
		 */
		noLocationsHint: () => LocalizedString
		/**
		 * Selected categories
		 */
		selectedCategories: () => LocalizedString
		/**
		 * Remove {name}
		 */
		removeCategory: (arg: { name: unknown }) => LocalizedString
		/**
		 * Edit
		 */
		edit: () => LocalizedString
		/**
		 * Select a store to manage it.
		 */
		noLocationSelectedHint: () => LocalizedString
		/**
		 * Select a store to manage it.
		 */
		noStoreSelectedHint: () => LocalizedString
		/**
		 * Are you sure you want to delete this store? This action cannot be undone.
		 */
		confirmDeleteStore: () => LocalizedString
		/**
		 * Are you sure you want to delete this location?
		 */
		confirmDeleteLocation: () => LocalizedString
		/**
		 * Active
		 */
		active: () => LocalizedString
		/**
		 * Inactive
		 */
		inactive: () => LocalizedString
		/**
		 * Store name is required
		 */
		storeNameRequired: () => LocalizedString
		/**
		 * Store created
		 */
		storeCreated: () => LocalizedString
		/**
		 * Store updated
		 */
		storeUpdated: () => LocalizedString
		/**
		 * Location created
		 */
		locationCreated: () => LocalizedString
		/**
		 * Location updated
		 */
		locationUpdated: () => LocalizedString
		/**
		 * Add Location
		 */
		addLocation: () => LocalizedString
		/**
		 * Location name is required
		 */
		locationRequired: () => LocalizedString
		/**
		 * Save Changes
		 */
		saveChanges: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
	}
	products: {
		/**
		 * Products
		 */
		pageTitle: () => LocalizedString
		/**
		 * Create Product
		 */
		createProduct: () => LocalizedString
		/**
		 * Edit Product
		 */
		editProduct: () => LocalizedString
		/**
		 * SKU
		 */
		productSku: () => LocalizedString
		/**
		 * Description
		 */
		productDescription: () => LocalizedString
		/**
		 * Category
		 */
		productCategory: () => LocalizedString
		/**
		 * Unit
		 */
		productUnit: () => LocalizedString
		/**
		 * Alert days before expiry
		 */
		productAlertDays: () => LocalizedString
		/**
		 * Notes
		 */
		productNotes: () => LocalizedString
		/**
		 * Barcode
		 */
		productBarcode: () => LocalizedString
		/**
		 * Add barcode
		 */
		addBarcode: () => LocalizedString
		/**
		 * Barcode added
		 */
		barcodeAdded: () => LocalizedString
		/**
		 * Barcode removed
		 */
		barcodeRemoved: () => LocalizedString
		/**
		 * No products yet
		 */
		noProducts: () => LocalizedString
		/**
		 * Search by SKU or description…
		 */
		searchPlaceholder: () => LocalizedString
		/**
		 * Search by scan or SKU…
		 */
		scanSearch: () => LocalizedString
		/**
		 * No barcode
		 */
		noBarcode: () => LocalizedString
		/**
		 * Archived products cannot receive new barcodes.
		 */
		archivedProducts: () => LocalizedString
		/**
		 * Categories
		 */
		categories: () => LocalizedString
		/**
		 * No category
		 */
		noCategory: () => LocalizedString
		/**
		 * Select category
		 */
		selectCategory: () => LocalizedString
		/**
		 * Unarchive
		 */
		unarchive: () => LocalizedString
		/**
		 * Archive
		 */
		archive: () => LocalizedString
		/**
		 * Archive product
		 */
		archiveProduct: () => LocalizedString
		/**
		 * Are you sure you want to archive this product? It will be hidden from the active list.
		 */
		confirmArchive: () => LocalizedString
		/**
		 * No products in this category.
		 */
		noProductsInCategory: () => LocalizedString
		/**
		 * No products match your search.
		 */
		noProductsMatchSearch: () => LocalizedString
		/**
		 * Inventory
		 */
		inventory: () => LocalizedString
		/**
		 * Total
		 */
		total: () => LocalizedString
		/**
		 * Add
		 */
		add: () => LocalizedString
		/**
		 * Subtract
		 */
		subtract: () => LocalizedString
		/**
		 * Set count
		 */
		setCount: () => LocalizedString
	}
	lotForm: {
		/**
		 * Create expiry lot
		 */
		createTitle: () => LocalizedString
		/**
		 * Edit expiry lot
		 */
		editTitle: () => LocalizedString
		/**
		 * Select product
		 */
		selectProduct: () => LocalizedString
		/**
		 * Select store
		 */
		selectStore: () => LocalizedString
		/**
		 * Select location
		 */
		selectLocation: () => LocalizedString
		/**
		 * Unit
		 */
		selectUnit: () => LocalizedString
		/**
		 * Quantity
		 */
		quantity: () => LocalizedString
		/**
		 * Quantity *
		 */
		quantityStar: () => LocalizedString
		/**
		 * Actual quantity in inventory *
		 */
		actualQuantity: () => LocalizedString
		/**
		 * Expiry date
		 */
		expiryDate: () => LocalizedString
		/**
		 * Notification date
		 */
		notificationDate: () => LocalizedString
		/**
		 * Alert days
		 */
		alertDays: () => LocalizedString
		/**
		 * Batch code
		 */
		batchCode: () => LocalizedString
		/**
		 * Notes
		 */
		notes: () => LocalizedString
		/**
		 * Save lot
		 */
		save: () => LocalizedString
		/**
		 * Saving…
		 */
		saving: () => LocalizedString
		/**
		 * Select a location
		 */
		selectLocationPrompt: () => LocalizedString
		/**
		 * No location selected
		 */
		noLocationSelected: () => LocalizedString
		/**
		 * A location is required to save this lot.
		 */
		requireLocationNote: () => LocalizedString
		/**
		 * YYYY-MM-DD
		 */
		dateFormat: () => LocalizedString
	}
	lotMovements: {
		/**
		 * Lot movements
		 */
		panelTitle: () => LocalizedString
		/**
		 * Movement history
		 */
		history: () => LocalizedString
		/**
		 * No movements yet.
		 */
		noMovements: () => LocalizedString
		/**
		 * Move stock
		 */
		moveStock: () => LocalizedString
		/**
		 * Register exit
		 */
		registerExit: () => LocalizedString
		/**
		 * Adjust count
		 */
		adjustCount: () => LocalizedString
		/**
		 * Quantity to add
		 */
		quantityToAdd: () => LocalizedString
		/**
		 * Quantity to remove
		 */
		quantityToRemove: () => LocalizedString
		/**
		 * Quantity to set
		 */
		quantityToSet: () => LocalizedString
		/**
		 * Reason
		 */
		reason: () => LocalizedString
		reasons: {
			/**
			 * Transfer
			 */
			transfer: () => LocalizedString
			/**
			 * Sold
			 */
			sold: () => LocalizedString
			/**
			 * Consumed
			 */
			consumed: () => LocalizedString
			/**
			 * Discarded
			 */
			discarded: () => LocalizedString
			/**
			 * Donated
			 */
			donated: () => LocalizedString
			/**
			 * Adjustment
			 */
			adjustment: () => LocalizedString
			/**
			 * Expired
			 */
			expired: () => LocalizedString
			/**
			 * Other
			 */
			other: () => LocalizedString
		}
		resolution: {
			/**
			 * Resolve quantity
			 */
			resolveQuantity: () => LocalizedString
			/**
			 * Consumed
			 */
			consumed: () => LocalizedString
			/**
			 * Sold
			 */
			sold: () => LocalizedString
			/**
			 * Discarded
			 */
			discarded: () => LocalizedString
			/**
			 * Donated
			 */
			donated: () => LocalizedString
			/**
			 * Other
			 */
			other: () => LocalizedString
			/**
			 * Resolution history
			 */
			resolutionHistory: () => LocalizedString
			/**
			 * No resolution events yet.
			 */
			noHistory: () => LocalizedString
			/**
			 * Loading history…
			 */
			loadingHistory: () => LocalizedString
		}
		/**
		 * Current inventory at this location: {current}
		 */
		currentInventory: (arg: { current: unknown }) => LocalizedString
		/**
		 * Available: {available}
		 */
		available: (arg: { available: unknown }) => LocalizedString
		/**
		 * Will increase inventory
		 */
		willIncrease: () => LocalizedString
		/**
		 * Will decrease inventory
		 */
		willDecrease: () => LocalizedString
		/**
		 *  (integers only)
		 */
		integerNote: () => LocalizedString
	}
	calendar: {
		/**
		 * Calendar
		 */
		pageTitle: () => LocalizedString
		/**
		 * Today
		 */
		today: () => LocalizedString
		/**
		 * This week
		 */
		thisWeek: () => LocalizedString
		/**
		 * This month
		 */
		thisMonth: () => LocalizedString
		/**
		 * Upcoming
		 */
		upcoming: () => LocalizedString
		/**
		 * Expiring
		 */
		expiring: () => LocalizedString
		/**
		 * No lots expiring on this date.
		 */
		noLotsOnDate: () => LocalizedString
	}
	backupRestore: {
		/**
		 * Backup & Restore
		 */
		pageTitle: () => LocalizedString
		/**
		 * Export backup
		 */
		exportSection: () => LocalizedString
		/**
		 * Creates a full copy of your database at a location you choose. The app remains open and usable during export.
		 */
		exportDesc: () => LocalizedString
		/**
		 * Export backup
		 */
		exportButton: () => LocalizedString
		/**
		 * Exporting…
		 */
		exporting: () => LocalizedString
		/**
		 * Restore from backup
		 */
		restoreSection: () => LocalizedString
		/**
		 * This is a destructive operation.
		 */
		restoreDesc: () => LocalizedString
		/**
		 * Make sure you have an export of your current data before proceeding.
		 */
		restoreWarning: () => LocalizedString
		/**
		 * Are you sure? This will permanently replace all current data with the backup.
		 */
		restoreConfirm: () => LocalizedString
		/**
		 * Restore from backup
		 */
		restoreButton: () => LocalizedString
		/**
		 * Restoring…
		 */
		restoring: () => LocalizedString
		/**
		 * About backups
		 */
		aboutSection: () => LocalizedString
		/**
		 * What is included?
		 */
		includesQ: () => LocalizedString
		/**
		 * Full database copy including all stores, products, expiry lots, categories, settings, and history.
		 */
		includesA: () => LocalizedString
		/**
		 * How often should I back up?
		 */
		howOftenQ: () => LocalizedString
		/**
		 * Regular backups are recommended before major changes like CSV imports or bulk lot operations.
		 */
		howOftenA: () => LocalizedString
		/**
		 * Where should I save backups?
		 */
		whereQ: () => LocalizedString
		/**
		 * Any location you choose — external drive, cloud folder, or local directory. Standard SQLite files can be opened with most database tools.
		 */
		whereA: () => LocalizedString
		/**
		 * Current database location
		 */
		locationQ: () => LocalizedString
		/**
		 * The active database is stored in the app's local data directory. The backup export lets you choose where to save your copy.
		 */
		locationA: () => LocalizedString
	}
	csvImport: {
		/**
		 * Import Products from CSV
		 */
		pageTitle: () => LocalizedString
		/**
		 * Select CSV file
		 */
		selectFile: () => LocalizedString
		/**
		 * Choose a CSV file to import products
		 */
		selectFileDesc: () => LocalizedString
		/**
		 * Expected columns
		 */
		expectedColumns: () => LocalizedString
		/**
		 * Tip:
		 */
		tip: () => LocalizedString
		/**
		 * Column headers are auto-detected. Common aliases are accepted.
		 */
		tipText: () => LocalizedString
		/**
		 * Map CSV Columns
		 */
		mapColumns: () => LocalizedString
		/**
		 * Field
		 */
		field: () => LocalizedString
		/**
		 * Column
		 */
		column: () => LocalizedString
		/**
		 * Preview
		 */
		preview: () => LocalizedString
		/**
		 * Required
		 */
		required: () => LocalizedString
		/**
		 * Import Preview
		 */
		importPreview: () => LocalizedString
		/**
		 * Total rows
		 */
		totalRows: () => LocalizedString
		/**
		 * Valid
		 */
		valid: () => LocalizedString
		duplicates: {
			/**
			 * Duplicate SKU
			 */
			sku: () => LocalizedString
			/**
			 * Duplicate barcode
			 */
			barcode: () => LocalizedString
		}
		/**
		 * Missing required
		 */
		missing: () => LocalizedString
		/**
		 * Conflict Strategy
		 */
		conflictStrategy: () => LocalizedString
		/**
		 * Row Details
		 */
		rowDetails: () => LocalizedString
		/**
		 * Description
		 */
		description: () => LocalizedString
		/**
		 * Status
		 */
		status: () => LocalizedString
		/**
		 * Detail
		 */
		detail: () => LocalizedString
		/**
		 * Import Complete
		 */
		importComplete: () => LocalizedString
		/**
		 * Created
		 */
		created: () => LocalizedString
		/**
		 * Updated
		 */
		updated: () => LocalizedString
		/**
		 * Skipped
		 */
		skipped: () => LocalizedString
		/**
		 * Invalid
		 */
		invalid: () => LocalizedString
		/**
		 * Import Log
		 */
		importLog: () => LocalizedString
		/**
		 * Import
		 */
		importButton: () => LocalizedString
		/**
		 * Importing…
		 */
		importing: () => LocalizedString
		conflictOptions: {
			/**
			 * Skip existing
			 */
			skip: () => LocalizedString
			/**
			 * Overwrite existing
			 */
			overwrite: () => LocalizedString
			/**
			 * Skip duplicates
			 */
			skipDuplicates: () => LocalizedString
		}
	}
	unitReview: {
		/**
		 * Unit Review
		 */
		pageTitle: () => LocalizedString
		/**
		 * {count} product{s} use non-standard units.
		 */
		unitCount: (arg: { count: unknown, s: unknown }) => LocalizedString
		/**
		 * Review unit
		 */
		reviewUnit: () => LocalizedString
		/**
		 * Keep
		 */
		keep: () => LocalizedString
		/**
		 * Keep as custom
		 */
		keepAsCustom: () => LocalizedString
		/**
		 * Map to standard
		 */
		mapToStandard: () => LocalizedString
		/**
		 * Preset units:
		 */
		presetUnits: () => LocalizedString
		/**
		 * Custom units:
		 */
		customUnits: () => LocalizedString
	}
	scan: {
		/**
		 * Search by scan or SKU…
		 */
		placeholder: () => LocalizedString
		/**
		 * Scan barcode or enter SKU
		 */
		ariaLabel: () => LocalizedString
		/**
		 * Press Enter to search
		 */
		title: () => LocalizedString
		/**
		 * No product found for this barcode.
		 */
		noMatch: () => LocalizedString
		/**
		 * Search failed: {msg}
		 */
		searchError: (arg: { msg: unknown }) => LocalizedString
	}
	categoryPicker: {
		/**
		 * Filter by category…
		 */
		placeholder: () => LocalizedString
		/**
		 * Search categories…
		 */
		searchPlaceholder: () => LocalizedString
		/**
		 * Selected categories
		 */
		selectedCategories: () => LocalizedString
		/**
		 * Remove {name}
		 */
		removeCategory: (arg: { name: unknown }) => LocalizedString
		/**
		 * Clear all
		 */
		clearAll: () => LocalizedString
		/**
		 * Clear all selected categories
		 */
		clearAllAria: () => LocalizedString
		/**
		 * Search categories
		 */
		searchAria: () => LocalizedString
		/**
		 * Close
		 */
		closeAria: () => LocalizedString
		/**
		 * Searching…
		 */
		searching: () => LocalizedString
		/**
		 * No categories yet
		 */
		noCategories: () => LocalizedString
		/**
		 * Creating…
		 */
		creating: () => LocalizedString
		/**
		 * Uncategorized
		 */
		uncategorized: () => LocalizedString
		/**
		 * No category
		 */
		noCategory: () => LocalizedString
		/**
		 * "{name}" already exists
		 */
		alreadyExists: (arg: { name: unknown }) => LocalizedString
		/**
		 * Create "{name}"
		 */
		createOption: (arg: { name: unknown }) => LocalizedString
	}
	notification: {
		/**
		 * ⚠️ Expiry alert: 
		 */
		titlePrefix: () => LocalizedString
		/**
		 * {qty} expires on {expiry_date} · {location}
		 */
		bodyTemplate: (arg: { expiry_date: unknown, location: unknown, qty: unknown }) => LocalizedString
	}
	pdf: {
		/**
		 * Caduxo Report
		 */
		documentTitle: () => LocalizedString
		/**
		 * Generated at
		 */
		generatedAt: () => LocalizedString
		/**
		 * Rows
		 */
		rows: () => LocalizedString
		/**
		 * Filters
		 */
		filters: () => LocalizedString
		/**
		 * Filters:
		 */
		filtersPrefix: () => LocalizedString
		/**
		 * No rows match the current report filters.
		 */
		emptyNotice: () => LocalizedString
		/**
		 * SKU
		 */
		columnSku: () => LocalizedString
		/**
		 * Description
		 */
		columnDescription: () => LocalizedString
		/**
		 * Store / Location
		 */
		columnStoreLocation: () => LocalizedString
		/**
		 * Qty
		 */
		columnQty: () => LocalizedString
		/**
		 * Expiry
		 */
		columnExpiry: () => LocalizedString
		/**
		 * Days
		 */
		columnDays: () => LocalizedString
		/**
		 * Alert
		 */
		columnAlert: () => LocalizedString
		/**
		 * Batch
		 */
		columnBatch: () => LocalizedString
		/**
		 * Caduxo · Expiry Tracker
		 */
		brand: () => LocalizedString
		/**
		 * Page {n} of {m}
		 */
		pageOf: (arg: { m: unknown, n: unknown }) => LocalizedString
		/**
		 * {n} ago
		 */
		daysAgo: (arg: { n: unknown }) => LocalizedString
	}
	errors: {
		/**
		 * An error occurred. Please try again.
		 */
		generic: () => LocalizedString
		/**
		 * Could not load data.
		 */
		loadFailed: () => LocalizedString
		/**
		 * Could not save. Please try again.
		 */
		saveFailed: () => LocalizedString
		/**
		 * Not found.
		 */
		notFound: () => LocalizedString
		/**
		 * Invalid {label} format: `{value}` (expected YYYY-MM-DD)
		 */
		invalidDateFormat: (arg: { label: unknown, value: unknown }) => LocalizedString
		/**
		 * Use YYYY-MM-DD
		 */
		dateUseIsoFormat: () => LocalizedString
		/**
		 * Year must be 1900–2100
		 */
		dateYearRange: () => LocalizedString
		/**
		 * This field is required
		 */
		dateFieldRequired: () => LocalizedString
		/**
		 * Invalid date
		 */
		dateInvalid: () => LocalizedString
	}
}

export type Formatters = {}
